pipeline {
    agent any

    stages {
        stage('Clone Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/heviiiiiii/HR-System.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('qiu_project') {
                    sh 'docker build -t heviiiiiii/app .'
                }
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker run -d -p 8081:80 heviiiiiii/app'
            }
        }
    }
}
