pipeline {
    agent any

    stages {
        stage('Clone Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/heviiiiiii/HR-System.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('qiu_project') {
                    bat 'docker build -t heviiiiiii/app .'
                }
            }
        }

        stage('Run Container') {
            steps {
                bat 'docker run -d -p 8081:80 heviiiiiii/app'
            }
        }
        stage('Docker Login & Push') {
    steps {
        bat 'docker login -u hevi -p YOUR_PASSWORD'
        bat 'docker push hevi/app'
    }
}
    }
}
